#ifndef SAMPLE_LIBRARY_CONFIG_H
#define SAMPLE_LIBRARY_CONFIG_H

#define CONF_SAMPLE_LIBRARY_SHARED_LIB 0

#if defined(SAMPLE_LIBRARY_BUILD_SHARED_LIB)
    #define CONF_SAMPLE_LIBRARY_BUILD_SHARED_LIB 1
#else
    #define CONF_SAMPLE_LIBRARY_BUILD_SHARED_LIB 0
#endif

#endif
